### ISSUE TITLE
Interest in including OrderedSet in python standard library?

### ISSUE THREAD

**Issue by jagerber48** [simonpercivall/orderedset#37]
Hello, I am interested to know if the maintainers of this package would have interest in including this functionality in the python standard library. It seems natural for `OrderedSet` to sit next to `OrderedDict` in the `collections` package. There is a discussion on the Python Discussion Forums. It is not clear-cut that it should be added but I wanted to gauge the interest of the folks maintaining the current Python ordered set implementations.

https://discuss.python.org/t/add-orderedset-to-stdlib/12730/15

**Comment by simonpercivall** [comment]
Hi!

1. A Cython package wouldn't ever get added to the stdlib;
2. there are several issues open for this package relating to edge cases in comparisons (to other sets, to other collections);
3. this library was written before the dict implementation in python was insertion ordered

I _do_ think it would be good to have an orderedset in the stdlib, but this library is probably not a good fit for it, and I'd rather have a new C implementation based on the implementation of `dict`.

**Comment by jagerber48** [comment]
I see, that information and feedback is very helpful, thank you!

**Comment by impredicative** [comment]
4. This library doesn't even work anymore. It doesn't install.
