### ISSUE TITLE
Reimplement based on naturally ordered sets?

### ISSUE THREAD

**Issue by xmo-odoo** [simonpercivall/orderedset#6]
The [new Pypy dict](http://morepypy.blogspot.be/2015/01/faster-more-memory-efficient-and-more.html) features natural ordering (by insertion order), faster iteration and reduced memory consumption.

It's based on [a design/concept by Raymond Hettinger on python-dev](https://mail.python.org/pipermail/python-dev/2012-December/123028.html) which he intended in big part [to use for sets](https://mail.python.org/pipermail/python-dev/2012-December/123207.html). Applying the design to a set avoids storing a bunch of extra doubly-linked-list pointers to provide iteration ordering.

**Comment by simonpercivall** [comment]
Sounds like a good idea, but currently out of scope for this implementation.
